name: Pheonic test automation workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Execution of API test framework
      run: mvn test -DsuiteXmlFile=testng.xml -Denv=qa
      
    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Surefire report
        path: target/surefire-reports/
        retention-days: 10

  
