name: Pheonic test automation workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "30 18 * * *"
    - cron: "30 17 * * *"
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        type: choice
        options: [qa,uat,dev]
        default: qa
        required: true

      suiteXmlFile:
        description: "Testng xml file"
        type: choice
        options: [testng.xml,smoketestng.xml,regressiontestng.xml]
        default: testng.xml
        required: true
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Default values for execution
      id: default
      run: |
            echo "suiteXmlFile=${{ github.event.inputs.suiteXmlFile || 'testng.xml'}}" >> $GITHUB_OUTPUT
            echo "env=${{ github.event.inputs.env || 'qa'}}" >> $GITHUB_OUTPUT
    - name: Execution of API test framework
      run: mvn test -DsuiteXmlFile="${{ steps.default.outputs.suiteXmlFile }}" -Denv="${{ steps.default.outputs.env }}"
      
    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Surefire report
        path: target/surefire-reports/
        retention-days: 10

  
